---
environment: test

serverPort: 8080

service:
  statusRefreshInterval: 10000
  statusRequestTimeout: 100

paths:
  health:
    default: /healtcheck
  meta:
    default: /_meta/version

services:
  - name: rms
    url: http://localhost:1080/rms
  - name: cms
    url: http://localhost:1080/cms    
  - name: mms
    url: http://localhost:1080/mms   
  - name: client
    url: http://localhost:1080/client   
  - name: dictionary
    url: http://localhost:1080/mms   
  - name: bff-api
    url: http://localhost:1080/cms 
  - name: cms4
    url: http://localhost:1080/cms   
  - name: cms2
    url: http://localhost:1080/cms  
  - name: fs-session-management
    url: http://localhost:1080/cms  
  - name: fs-filemanager
    url: http://localhost:1080/cms
  - name: fs-rms-onboarding
    url: http://localhost:1080/cms  
  - name: fs-rms-fraudprevention
    url: http://localhost:1080/cms

  - name: fs-rvention1
    url: http://localhost:1080/cms

  - name: fs-rms-fraudprevention2
    url: http://localhost:1080/cms

  - name: fs-rms-fprevention3
    url: http://localhost:1080/cms

  - name: ftion4
    url: http://localhost:1080/cms

  - name: fs-rms-frauevention5
    url: http://localhost:1080/cms

  - name: fsion6
    url: http://localhost:1080/cms

  - name: fs-rms-fprevention7
    url: http://localhost:1080/cms